### PR TITLE
User Can Create an Account

### PR DESCRIPTION
**Pull request by tshililopercy**
A user can create an account with details stored in the Mssql database... User is allowed to proceed to the home page after successfully creating an Account or given Error Message with Tips To create account successfully.

### CODE REVIEW

**Review by JohnRatcliffe209 — CHANGES_REQUESTED** [review]
The functionality seems to be working correctly. Username must be unique, passwords are hashed etc. However, i don't seem to understand how the user is able to reach the sign up page. In order to test the functionality I had to explicitly type in /signUp in the url. Perhaps I missed something, if not please could you add this.

**Comment by tshililopercy** [comment]
@JohnRatcliffe209 Yes it should be the first page user interact with, however since sign in is not complete... How will the User proceed ?

**Comment by Thendo2000** [comment]
@JohnRatcliffe209 perhaps I can provide the link in my html code to the Sign-up page if the user does not have an account. The sign-in page can be what first appears for the user. Otherwise @tshililopercy the code looks good, the quality of the tests is well done.

**Comment by Thendo2000** [comment]
@tshililopercy Only saw your latest comment now, yeah the sign-up page can also be the first thing that appears for the users

**Comment by tshililopercy** [comment]
@JohnRatcliffe209 @Thendo2000  What i can do presently is proceeding to the home page after successfully creating an account, is it fine  for now?

**Comment by Thendo2000** [comment]
@tshililopercy yeah that's fine

**Review by JohnRatcliffe209 — APPROVED** [review]
I see where you were going with it. I appreciate this update though.

**Comment by SphumeleleSijadu** [comment]
The code meets it's functionality requirements by hashing the password, as well as preventing 2 users from creating an account with the same name.
As mentioned above the only thing left is integration with the rest of the program.

**Pull request merged**
