### PR TITLE
minor features added with sign in functionality

### PR DESCRIPTION
**Pull request by Thendo2000**

### CODE REVIEW

**Review by JohnRatcliffe209 — CHANGES_REQUESTED** [review]
This is great, however could you please add this for the 'result', 'resultMulti' and 'log' pages.

**Comment by Thendo2000** [comment]
the logout button?

**Comment by JohnRatcliffe209** [comment]
> the logout button?

No, I mean so that one can only access those pages when logged in. Otherwise it will allow an undefined user to access the log etc.

**Comment by Thendo2000** [comment]
Ok, restricted more webpages now

**Review by tshililopercy — APPROVED** [review]
It's working good.

**Review by JohnRatcliffe209 — APPROVED** [review]

**Pull request merged**
