### PR TITLE
User can play multiplayer with 2 other players

### PR DESCRIPTION
**Pull request by tshililopercy**
A user can now play multiplayer with other two users seeing their usernames as well.

To Test This:
Because Sessions are used and you are testing using one bowser(they will change)
1. log into one go all the way and select multiplayer.
2. Log into second one and go all the way and select multiplayer
3. Log into the third one and go all the way and select multiplayer
( Going all the way is done to make sure the session username is taken by the client code, as one browser is being used )

### CODE REVIEW

**Review by lethiwe6 — COMMENTED** [review]
Playing with other 2 players works however it shows the user name for only 1 player in all grids maybe it's because of playing from the same computer and I'm not if a minimum of 2 players can still play.

**Review by JohnRatcliffe209 — COMMENTED** [review]
So the functionality of the game seems to be working correctly for 3 players. As Lethiwe mentioned, the player ID above the board is the same. Perhaps you could rather label them as Opponent 1 and Opponent 2 to make things simpler.

**Comment by tshililopercy** [comment]
@lethiwe6 Is because of that, to test well follow  the instructions listed.

**Comment by tshililopercy** [comment]
@JohnRatcliffe209 The problem with that opponent 1,opponent 2...you won't   know who won specifically.

**Review by JohnRatcliffe209 — APPROVED** [review]

**Pull request merged**
