### PR TITLE
Created sign in functionality

### PR DESCRIPTION
**Pull request by Thendo2000**

### CODE REVIEW

**Comment by SphumeleleSijadu** [comment]
The sign up page is well integrated with the rest of the game.
I just don't know where I should go if I want to login with an existing account. 
Or will that be in the next sprint?

**Comment by Thendo2000** [comment]
@SphumeleleSijadu if you have created an account on the sign up page it should sign you in if you entered your details correctly

**Review by JohnRatcliffe209 — COMMENTED** [review]
I believe there is a link under the input fields.
Besides that, as an added feature for next sprint, it would be nice if the sign in feature would make use of cookies potentially, which will help with retrieving information from the database, such as the score.

**Comment by Thendo2000** [comment]
@JohnRatcliffe209 yeah definitely, I plan on implementing that next sprint

**Review by tshililopercy — COMMENTED** [review]
I tested it the functionality is working pretty good, A user can sign Up and be able to Login with the registered details... 

You can can perhaps add Sign In Unit Testing.

**Comment by Thendo2000** [comment]
I was not too sure what I could possibly test, but I'll look into it

**Comment by tshililopercy** [comment]
> I was not too sure what I could possibly test, but I'll look into it

Okay great, you can have a look on the Sign Up tests.

**Pull request merged**
