### PR TITLE
Lethiwe

### PR DESCRIPTION
**Pull request by lethiwe6**
A Player can generate a  Unique room ID and another player can user the room ID generated by the host player to join the Game.

### CODE REVIEW

**Comment by SphumeleleSijadu** [comment]
There may be something wrong on my end but it seems as if the game is not running.
Could you possibly comment on how to run the code or which sections work?

**Review by JohnRatcliffe209 — CHANGES_REQUESTED** [review]
I believe the problem is that this branch is very far behind main. @lethiwe6 you need to merge main into your branch to keep it updated. This will allow us to see how your code works with the current state of the game.

**Comment by lethiwe6** [comment]
okay Let me save the changes somewhere else and add changes to the latest code, make another pull request and close this one

**Comment by lethiwe6** [comment]
merging the latest code

**Pull request closed without merging**
