### PR TITLE
User is able to access the log

### PR DESCRIPTION
**Pull request by JohnRatcliffe209**

### CODE REVIEW

**Comment by SphumeleleSijadu** [comment]
I am struggling to run the code due to the conflicts. 
Could you try and fix them and make another pull request?

I was eventually able to run index.js and I accessed the log.
It kept track of who last logged in and accessed the log.

I may be wrong but wasn't the log supposed to display the ranking of each player?

**Comment by JohnRatcliffe209** [comment]
> I am struggling to run the code due to the conflicts. Could you try and fix them and make another pull request?
> 
> I was eventually able to run index.js and I accessed the log. It kept track of who last logged in and accessed the log.
> 
> I may be wrong but wasn't the log supposed to display the ranking of each player?

I believe the purpose of the log is to display actions taken by players, not the score or ranking. The conflicts don’t affect the running of the code, if you run my branch.

**Review by tshililopercy — APPROVED** [review]
It All looks good, Approved.

**Review by Thendo2000 — APPROVED** [review]
The log appears functional and everything looks good

**Pull request merged**
