### PR TITLE
Added Functionalities handling Guesses and Evaluating Guesses on the server. 

### PR DESCRIPTION
**Pull request by tshililopercy**

### CODE REVIEW

**Comment by Thendo2000** [comment]
Looks good, but it seems like you are still are using the singleplayer.js code before it was updated.

**Comment by tshililopercy** [comment]
@Thendo2000 It compared it with the current main, please recheck the changes on that file as compared to the one in main branch (i think it's updated)

**Comment by Thendo2000** [comment]
@tshililopercy yeah I checked it's updated.

**Review by JohnRatcliffe209 — CHANGES_REQUESTED** [review]
You need to resolve the merge conflicts before it can be merged.

**Comment by tshililopercy** [comment]
I resolved them.

**Review by JohnRatcliffe209 — APPROVED** [review]
Perfect. Looks good now.

**Pull request merged**
