### PR TITLE
Player can leave lobby to choose another game mode 

### PR DESCRIPTION
**Pull request by lethiwe6**

### CODE REVIEW

**Comment by SphumeleleSijadu** [comment]
The button to leave the lobby seems to be working fine.
However, the rest of multiplayer functionality doesn't seem to work.
I can't joint the game using the generated code and the keyboard isn't visible.
It may be just my computer, but please check that the rest of the game works before you merge.

**Review by tshililopercy — CHANGES_REQUESTED** [review]
Please use the multiplayer.js to add your functionality, the lobby.js won't work/ export your Functions from Lobby to multiplayer.js

**Review by JohnRatcliffe209 — APPROVED** [review]
This is working correctly now.

**Review by Thendo2000 — APPROVED** [review]
Button is working correctly

**Review by tshililopercy — APPROVED** [review]
It's working Correctly

**Pull request merged**
